admin_panel/admin_panel/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static

from admin_panel.telebot.admin import bot_admin

urlpatterns = [
    path("tgbot/", include("admin_panel.telebot.urls", namespace="panel")),
    path("config/", include("admin_panel.liveconfigs.urls", namespace="config")),
    path("", bot_admin.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin_panel/telebot/urls.py
from django.urls import path

from . import views

app_name = "panel"

urlpatterns = [
    path('mailing', views.mailing, name='mailing'),
]

admin_panel/templates/tgbot/form_mailing.html
{% extends "admin/base_site.html" %}
{% load static %}
{% block content %}
    <div class="col-md-12">
        <form id="send_form " method="post" action="{% url 'panel:mailing' %}" enctype="multipart/form-data">
            <div class="card card-info">
                <div class="card-body">
                    <fieldset class="module aligned {{ fieldset.classes }}">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-row field-{{ field.name }}" id="{{ field.name }}_div"
                                 style="{{ field.field.widget.attrs.style_attribute }}">
                                <div>
                                    <div class="flex-container">
                                        {% if field.is_checkbox %}
                                            {{ field }}{{ field.label_tag }}
                                        {% else %}
                                            {{ field.label_tag }} {{ field }}
                                        {% endif %}
                                    </div>
                                    {% if field.help_text %}
                                        <div class="help"{% if field.id_for_label %}
                                             id="{{ field.id_for_label }}_helptext"{% endif %}>
                                            <div>{{ field.help_text|safe }}</div>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                    </fieldset>
                </div>
                <div class="submit-row">
                    <input type="submit" value="Отправить рассылку" class="default">
                </div>
            </div>
        </form>
    </div>
    <link rel="stylesheet" href="{% static "admin/css/forms.css" %}">
    <script src="{% static 'tgbot/js/jquery.min.js' %}"></script>
    <script src="{% static 'tgbot/js/mailing.js' %}"></script>
{% endblock %}